### ISSUE TITLE
find_vm_kernel_addrperm fails on iPad3,4 8.4.1

### ISSUE THREAD

**Issue by Samgisaninja** [jndok/OF32#1]
Hello,
Forgive me if I'm doing this wrong, this is the first issue I have ever reported on github.
I used this to find offsets for the iPad3,4 8.4.1, and it was unable to get the offset for find_vm_kernel_addrperm. I've attached the output below:

```console
Sams-MacBook-Air:OF32-master samuelgardner$ ./OF32 /Users/samuelgardner/Downloads/odysseus-0.999.0/macos/kernelcache.release.p101 
(+) Opening 'kernelcache.release.p101', found in /Users/samuelgardner/Downloads/odysseus-0.999.0/macos/kernelcache.release.p101
(+) Successfully mapped and validated kernelcache. Dumping offsets...

[OSSerializer_serialize   ]: 0x2d9864
[OSSymbol_getMetaClass    ]: 0x2db984
[calend_gettime           ]: 0x1d300
[bufattr_cpx              ]: 0xc65f4
[clock_ops                ]: 0x8007f11b
[copyin                   ]: 0xb386c
[bx_lr                    ]: 0xc65f6
[write_gadget             ]: 0xb35a8
Assertion failed: (n), function find_vm_kernel_addrperm, file of32.c, line 209.
Abort trap: 6
```

If you need any additional information, please let me know.

**Comment by Samgisaninja** [comment]
It also might just be beacuse 8.4.1 is different than other versions

**Comment by ghost** [comment]
Nope it happend to me on another model! you are not alone.

>AJWs-iMac:OF32 ajw$ ./OF32 /Users/ajw/Desktop/iPad2\,5-Kernalcache-Decrypted/kernelcache.release.p105 
(+) Opening 'kernelcache.release.p105', found in /Users/ajw/Desktop/iPad2,5-Kernalcache-Decrypted/kernelcache.release.p105
(+) Successfully mapped and validated kernelcache. Dumping offsets...

[OSSerializer_serialize   ]: 0x2d4a1c
[OSSymbol_getMetaClass    ]: 0x2d6afc
[calend_gettime           ]: 0x1d0a0
[bufattr_cpx              ]: 0xc3718
[clock_ops                ]: 0x324910
[copyin                   ]: 0xb1744
[bx_lr                    ]: 0xc371a
[write_gadget             ]: 0xb1488
Assertion failed: (n), function find_vm_kernel_addrperm, file of32.c, line 209.
Abort trap: 6

**Comment by Samgisaninja** [comment]
@Austcool-Walker What iOS version were you attempting to use for that?

**Comment by jndok** [comment]
I did not test on 8.4.1, the function fails because it does not find the symbol used as a starting point for the lookup.

I guess the symbol exists in iOS 9.x but not before. Will fix this soon.

**Comment by ghost** [comment]
I believe I'm also on 8.4.1 but I'm not entirely sure.

**Comment by Samgisaninja** [comment]
I was able to comment the lines that referenced addrmperm and rerun make, it found all the other offsets and the values matched the ones I found manually.

**Comment by stek29** [comment]
What is the correct offset?

**Comment by stek29** [comment]
@Samgisaninja Does #3 work?

**Comment by stek29** [comment]
```
[OSSerializer_serialize   ]: 0x2d9864
[OSSymbol_getMetaClass    ]: 0x2db984
[calend_gettime           ]: 0x1d300
[bufattr_cpx              ]: 0xc65f4
[clock_ops                ]: 0x8007f11b
[copyin                   ]: 0xb386c
[bx_lr                    ]: 0xc65f6
[write_gadget             ]: 0xb35a8
[vm_kernel_addrperm       ]: 0x3f7ef8
[kernel_pmap              ]: 0x3a711c
[flush_dcache             ]: 0xa7758
[invalidate_tlb           ]: 0xb3600
[setreuid                 ]: 0xfffffffd
[proc_ucred               ]: 0x8c
[task_for_pid             ]: 0x2c05c8
[allproc                  ]: 0x3f9efc
```

`clock_ops` and `setreuid` are weird too.

**Comment by Samgisaninja** [comment]
Clockops should be 0x8007f11b and addrperm is 0x3F8258

But I could be wrong

**Comment by Samgisaninja** [comment]
Given that Tihmstar has created a fork of this specifically for use on 8.4.1, I'm closing this issue.
